### ISSUE TITLE
Bug: Scroll handler is not properly setup initially for zooming

### ISSUE THREAD

**Issue by ronhitchens** [overstory/sw-poc#29]
The event handler bodyMouseEnter() should fire after D3 has initialized, but before any zoom event happen.  Something has changes so that this is no longer happening on page load.  It is not essential that this event happen on mouseenter for the body element, but the action should happen before any zoom events are fired.

Also, the dreaded double-click zoom behavior is back, also because this event did not fire to configure the zoom handlers.

**Comment by smagu** [comment]
I can reproduce this on my environment and also have final needed behaviour. 
It seems that this is only happening when mouse scroll event starts before "normal" behaviour is captures. I will try to move the capture of default scroll behaviour earlier in Angular Lifecycles - I believe this should solve the problem once and for all. 

https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

**Comment by ronhitchens** [comment]
This is still not working properly.  Leaving the mouse on the canvas area, then pressing Refresh (Cmd-R) refreshes the page.  Doing a wheel scroll after refresh causes the canvas to zoom in/out rather than scrolling the whole page.  Waiting a couple of seconds and scrolling again gives the expected whole-page scroll.

We are still not apparently getting a first event triggered to set the handler toggle state.  It's better but still not 100% right.  Leaving this as an open bug for now.
